services:
  app:
    image: mysociety/appg-membership:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/appg_membership      
    volumes:
      - ./:/workspaces/appg_membership/