source "https://rubygems.org"

# Explicitly specify Ruby version to help bundler resolve dependencies
ruby "~> 2.7.1"

# needed for newer versions of ruby locally
gem 'webrick'

# Use a specific Jekyll version compatible with Ruby 2.7
gem "jekyll", "~> 3.9.2"

# This is the default theme for new Jekyll sites
gem "minima", "~> 2.0"

# Use specific nokogiri version compatible with Ruby 2.7
gem "nokogiri", "~> 1.15.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-theme-slate"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?

# kramdown v2 ships without the gfm parser by default
gem "kramdown-parser-gfm"

# Lock http_parser.rb gem to v0.6.x on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Use a compatible version of the GitHub Pages gem
gem "github-pages", "~> 226", group: :jekyll_plugins